server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yu123456
    url: jdbc:mysql://localhost:3306/zuopin?serverTimezone=UTC
  thymeleaf:
    prefix: classpath:\templates\pages\
    suffix: .html
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.comm.pojo
  mapper-locations: classpath:/mapper/*Mapper.xml
